# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Nightly build

on:
  schedule:
  - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        id: maven_build
        run: mvn -B package --file pom.xml
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: phours-${{ matrix.os }}
          path: shade/phours.jar
      
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get current date
        id: get_date
        run: |
          echo "::set-output name=build_date::$(date +%Y%m%d%H%M%S)"
          echo "::set-output name=release_date::$(date)"
      - name: Get pre-release tag
        id: get_tag
        run: echo "::set-output name=git_tag::v0.4-alpha"
      - name: Get upload url for assets
        id: get_url
        run: |
          echo "::set-output name=upload_url::$($GITHUB_ACTION_PATH/get_upload_url.sh)"
          echo "${{ steps.get_url.outputs.upload_url }}"
      - name: Check if release for nightlies already exists
        id: check_release
        if: steps.get_url.outputs.upload_url != ''
        run: echo "::set-output name=release_exists::true"
      - name: Clear assets if release exists
        id: clear_assets
        if: steps.check_release.outputs.release_exists == true
        run: echo "Clear assets"
      - name: Download windows build
        id: download_artifacts_win
        uses: actions/download-artifact@v2
        with:
          name: phours-windows-latest
          path: windows
      - name: Download linux build
        id: download_artifacts_linux
        uses: actions/download-artifact@v2
        with:
          name: phours-ubuntu-latest
          path: linux
      - name: Download mac build
        id: download_artifacts_mac
        uses: actions/download-artifact@v2
        with:
          name: phours-macOS-latest
          path: macos
      - name: Create Release
        id: create_release
        if: steps.check_release.outputs.release_exists == false
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v0.4-alpha
          release_name: Nightly build
          draft: false
          prerelease: true
          body: Nightly build ${{ steps.get_date.outputs.release_date }}
      - name: Upload Windows Release
        id: upload-release-asset-win
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: windows/phours.jar
          asset_name: PHours-windows_${{ steps.get_date.outputs.build_date }}.jar
          asset_content_type: application/java-archive
      - name: Upload Linux Release
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: linux/phours.jar
          asset_name: PHours-linux_${{ steps.get_date.outputs.build_date }}.jar
          asset_content_type: application/java-archive
      - name: Upload MacOS Release
        id: upload-release-asset-mac
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: macos/phours.jar
          asset_name: PHours-macos_${{ steps.get_date.outputs.build_date }}.jar
          asset_content_type: application/java-archive
